config/routes.rb
Rails.application.routes.draw do
  get 'inquiry/new'
  post 'inquiry/edit'
  post 'inquiry/confirm'
  post 'inquiry/thanks'
  ActiveAdmin.routes(self)
  devise_for :users
  root to: "home#top"
  resources :posts do
    collection do
      get "novel"
      get "movie"
      get "comic"
      get "anime"
      get "search"
    end
    post "/reactions/:id", to: "reactions#create", as: "reactions"
    delete "/reactions/:id", to: "reactions#destroy"
  end
  get "/users/show", to: "users#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  include ActiveHash::Associations
  self.data = [
    { id: 1, name: "小説" },
    { id: 2, name: "映画" },
    { id: 3, name: "マンガ" },
    { id: 4, name: "アニメ" }
  ]
  has_many :posts
end

app/models/comment.rb
class Comment < ActiveHash::Base
  include ActiveHash::Associations
  self.data = [
    { id: 1, name: "その気持ち、わかります！" },
    { id: 2, name: "その作品、気になります！" },
    { id: 3, name: "その考え、面白いですね！" }
  ]
  has_many :reactions
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :name_kana, :email, :message

  with_options presence: { message: "を入力してください" } do
    validates :name
    validates :name_kana
    validates :email
    validates :message
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :reactions, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category

  with_options presence: true do
    validates :title
    validates :content
    validates :category
  end

  validates :spoiler, inclusion: [true, false]
  validates :content, length: { maximum: 4000 }

  def self.search(keyword)
    if keyword != ""
      Post.where("title LIKE(?)", "%#{keyword}%")
    else
      Post.all
    end
  end
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :user
  belongs_to :post

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :comment

  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :reactions

  validates :name, presence: true
  PASSWORD_REGEX = /\A(?=.*?[a-zA-Z])(?=.*?[\d])\w{6,12}\z/.freeze
  validates :password, format: { with: PASSWORD_REGEX, message: "は6文字以上12文字以下で英数字混合で入力してください", on: :create }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def authenticate_admin
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def new
    @inquiry = Inquiry.new
  end

  def edit
    @inquiry = Inquiry.new(inquiry_params)
  end

  def confirm
    @inquiry = Inquiry.new(inquiry_params)
    render :new unless @inquiry.valid?
  end

  def thanks
    @inquiry = Inquiry.new(inquiry_params)
    InquiryMailer.send_mail(@inquiry).deliver
  end

  private

  def inquiry_params
    params.require(:inquiry).permit(:name, :name_kana, :email, :message)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :move_to_sign_in, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :posted_user?, only: [:edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    if @post.destroy
      redirect_to posts_path
    else
      render :show
    end
  end

  def novel
    @posts = Post.where(category_id: 1).order("created_at DESC")
  end

  def movie
    @posts = Post.where(category_id: 2).order("created_at DESC")
  end

  def comic
    @posts = Post.where(category_id: 3).order("created_at DESC")
  end

  def anime
    @posts = Post.where(category_id: 4).order("created_at DESC")
  end

  def search
    @keyword = params[:keyword]
    @posts = Post.search(@keyword)
  end

  private

  def move_to_sign_in
    redirect_to new_user_session_path unless user_signed_in?
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def posted_user?
    redirect_to post_path(params[:id]) unless @post.user_id == current_user.id
  end

  def post_params
    params.require(:post).permit(
      :title,
      :content,
      :spoiler,
      :category_id
    ).merge(user_id: current_user.id)
  end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  def create
    @reaction = Reaction.new(comment_id: params[:id], post_id: params[:post_id], user_id: current_user.id)
    @reaction.save
  end

  def destroy
    @reaction = Reaction.find_by(comment_id: params[:id], post_id: params[:post_id], user_id: current_user.id)
    @reaction.destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    redirect_to posts_path unless user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.erb
<div class="top-title-image">
  <div class="top-title">
    <div class="container d-flex align-items-center h-100">
      <div class="row justify-content-center">
        <div class="top-title-heading col-6 text-center text-white display-2">
          テイルズ
        </div>
        <div class="w-100"></div>
        <div class="top-title-heading col-6 text-center text-white lead">
          ~好きな物語への愛を語るサイト~
        </div>
        <div class="w-100"></div>
        <div class="row justify-content-center mt-2">
          <% if user_signed_in? %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"col-2 btn btn-danger m-1 border" %>
          <% else %>
            <%= link_to "新規登録", new_user_registration_path, class:"col-1 btn btn-primary m-1 border" %>
            <%= link_to "ログイン", new_user_session_path, class:"col-1 btn btn-success m-1 border" %>
          <% end %>
        </div>
        <div class="w-100"></div>
        <%= link_to "みんなの投稿を見てみる！", posts_path, class:"col-2 btn btn-info m-1 border" %>
      </div>
    </div>
  </div>
</div>

<div class="top-about container-fluid">
  <div class="container py-5">
    <div class="row justify-content-center mx-auto text-center py-5">
      <div class="about-heading col-5 border-bottom">
        このサイトについて
      </div>
      <div class="w-100"></div>
      <div class="col-5">
        <p>好きなものについて心おきなく語れて、それを聞いてくれる人がいる</p>
        <p>そういう場所を、このサイトは目指しています。</p>
        <br>
        <p>その物語に出会えたことがたまらなく嬉しくて</p>
        <p>その物語が終わってしまったことが少し寂しい</p>
        <p>そんな気持ちになったことはありませんか？</p>
        <p>誰しも、お気に入りの物語がきっとあると思います</p>
        <p>あなたの好きな物語のお話を、聞かせてください</p>
      </div>
    </div>
  </div>
</div>

<div class="top-points container-fluid">
  <div class="container py-5">
    <div class="points-heading mx-auto w-50 text-center display-6 py-5">
      このサイトの特徴
    </div>
    <div class="w-100"></div>
    <div class="row py-5">
      <div class="col-4">
        <div class="point-heading text-center lead">匿名での投稿</div>
        <div class="w-75 mx-auto pt-4 text-center">
          アカウント名もアイコンも一切公開されず、完全に匿名で投稿できます。他人にどう思われるか、自分のキャラに合っているかなど気にすることなく投稿できます。
        </div>
      </div>
      <div class="col-4">
        <div class="point-heading text-center lead">投稿がみんなポジティブ</div>
        <div class="w-75 mx-auto pt-4 text-center">
          みんなが好きなものの好きなところを語る場所です。作品に対する批判的なレビューを目にすることはありません。
        </div>
      </div>
      <div class="col-4">
        <div class="point-heading text-center lead">３種類のリアクションボタン</div>
        <div class="w-75 mx-auto pt-4 text-center">
          コメント機能がないため、自分の投稿に対して誹謗中傷が寄せられることはありません。コメントの代わりに、気になった投稿にはどんどんリアクションボタンを押しましょう。
        </div>
      </div>
    </div>
  </div>
</div>

<div class="top-start container-fluid">
  <div class="container py-5">
    <div class="row justify-content-center py-5">
      <div class="col-5 text-right">
        <div class="top-start-heading">
          さあ、はじめましょう
        </div>
        <div class="m-3">投稿を見るだけならアカウント登録は不要です。</div>
      </div>
      <div class="col-5 text-center">
        <% if !user_signed_in? %>
          <%= link_to "新規登録", new_user_registration_path, class:"btn btn-primary btn-lg m-1 border" %>
          <%= link_to "ログイン", new_user_session_path, class:"btn btn-success btn-lg m-1 border" %>
        <% end %>
        <%= link_to "みんなの投稿を見てみる！", posts_path, class:"btn btn-info btn-lg m-1 border" %>
      </div>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/inquiry/confirm.html.erb
<%= render "shared/header" %>

<div class="inquiry-wrapper container">
  <%= form_with model: @inquiry, url: inquiry_thanks_path, local: true, class:"row justify-content-center" do |f| %>
    <div class="text-center lead mt-5">
      <h1>お問い合わせ内容の確認</h1>
    </div>

    <div class="form-group row justify-content-center">
      <div class="col-8 my-3">
        お名前
      </div>
      <div class="col-8">
        <%= f.hidden_field :name %>
        <%= @inquiry.name %>
      </div>
    </div>

    <div class="form-group row justify-content-center">
      <div class="col-8 my-3">
        お名前（ふりがな）
      </div>
      <div class="col-8">
        <%= f.hidden_field :name_kana %>
        <%= @inquiry.name_kana %>
      </div>
    </div>

    <div class="form-group row justify-content-center">
      <div class="col-8 my-3">
        メールアドレス
      </div>
      <div class="col-8">
        <%= f.hidden_field :email %>
        <%= @inquiry.email %>
      </div>
    </div>

    <div class="form-group row justify-content-center">
      <div class="col-8 my-3">
        お問い合わせ内容
      </div>
      <div class="col-8">
        <%= f.hidden_field :message %>
        <%= @inquiry.message %>
      </div>
    </div>

    <div class="form-group row justify-content-center">
      <%= f.submit "送信", class:"btn btn-primary col-3 my-3" %>
    </div>

  <% end %>
  <%= form_with model: @inquiry, url: inquiry_edit_path, local: true, class:"row justify-content-center" do |f| %>
    <%= f.hidden_field :name %>
    <%= f.hidden_field :name_kana %>
    <%= f.hidden_field :email %>
    <%= f.hidden_field :message %>
    <div class="form-group row justify-content-center">
      <%= f.submit "入力内容を変更する", class:"btn btn-secondary btn-sm col-2" %>
    </div>
  <% end %>
</div>

app/views/inquiry/edit.html.erb
<%= render "shared/header" %>

<div class="inquiry-wrapper container">
  <%= form_with model: @inquiry, url: inquiry_confirm_path, local: true, class:"row justify-content-center" do |f| %>
    <div class="text-center lead mt-5">
      <h1>お問い合わせ</h1>
    </div>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="form-group row justify-content-center">
      <%= f.label :name, "お名前", class:"col-8" %>
      <%= f.text_field :name, autofocus: true, autocomplete: "off", class:"col-8 my-3" %>
    </div>

    <div class="form-group row justify-content-center">
      <%= f.label :name_kana, "お名前（ふりがな）", class:"col-8" %><br />
      <%= f.text_field :name_kana, autocomplete: "off", class:"col-8 my-3" %>
    </div>

    <div class="form-group row justify-content-center">
      <%= f.label :email, "メールアドレス", class:"col-8" %><br />
      <%= f.text_field :email, autocomplete: "off", class:"col-8 my-3" %>
    </div>

    <div class="form-group row justify-content-center">
      <%= f.label :message, "お問い合わせ内容", class:"col-8" %><br />
      <%= f.text_area :message, autocomplete: "off", rows: "5", class:"col-8 my-3 p-1" %>
    </div>

    <div class="form-group row justify-content-center">
      <%= f.submit "確認画面へ進む", class:"btn btn-primary col-3 my-3" %>
    </div>
  <% end %>
</div>

app/views/inquiry/new.html.erb
<%= render "shared/header" %>

<div class="inquiry-wrapper container">
  <%= form_with model: @inquiry, url: inquiry_confirm_path, local: true, class:"row justify-content-center" do |f| %>
    <div class="text-center lead mt-5">
      <h1>お問い合わせ</h1>
    </div>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="form-group row justify-content-center">
      <%= f.label :name, "お名前", class:"col-8" %>
      <%= f.text_field :name, autofocus: true, autocomplete: "off", class:"col-8 my-3" %>
    </div>

    <div class="form-group row justify-content-center">
      <%= f.label :name_kana, "お名前（ふりがな）", class:"col-8" %><br />
      <%= f.text_field :name_kana, autocomplete: "off", class:"col-8 my-3" %>
    </div>

    <div class="form-group row justify-content-center">
      <%= f.label :email, "メールアドレス", class:"col-8" %><br />
      <%= f.text_field :email, autocomplete: "off", class:"col-8 my-3" %>
    </div>

    <div class="form-group row justify-content-center">
      <%= f.label :message, "お問い合わせ内容", class:"col-8" %><br />
      <%= f.text_area :message, autocomplete: "off", rows: "5", class:"col-8 my-3 p-1" %>
    </div>

    <div class="form-group row justify-content-center">
      <%= f.submit "確認画面へ進む", class:"btn btn-primary col-3 my-3" %>
    </div>
  <% end %>
</div>

app/views/inquiry/thanks.html.erb
<%= render "shared/header" %>

<div class="inquiry-wrapper container">
  <div class="row align-items-center h-100">
    <div class="col text-center">
      <p>お問い合わせいただきありがとうございました。</p>
      <p>お返事にしばらくお時間をいただく場合がございます。</p>
      <p>ご了承ください。</p>
      <%= link_to "投稿一覧ページへ戻る", posts_path %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-177224360-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-177224360-1');
    </script>
    <title>Original28394</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css2?family=M+PLUS+1p&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/anime.html.erb
<%= render "shared/header" %>

<div class="index-title d-flex align-items-center justify-content-center">
  <div class="h1 text-center text-white font-weight-bold">アニメについての投稿</div>
</div>

<% breadcrumb :anime %>
<%= breadcrumbs separator: " &rsaquo; " %>

<div class="container-fluid py-5">
  <div class="container">
    <%= render "shared/index", posts: @posts %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/posts/comic.html.erb
<%= render "shared/header" %>

<div class="index-title d-flex align-items-center justify-content-center">
  <div class="h1 text-center text-white font-weight-bold">マンガについての投稿</div>
</div>

<% breadcrumb :comic %>
<%= breadcrumbs separator: " &rsaquo; " %>

<div class="container-fluid py-5">
  <div class="container">
    <%= render "shared/index", posts: @posts %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/posts/index.html.erb
<%= render "shared/header" %>

<div class="index-title d-flex align-items-center justify-content-center">
  <div class="h1 text-center text-white font-weight-bold">投稿一覧ページ</div>
</div>

<% breadcrumb :posts %>
<%= breadcrumbs separator: " &rsaquo; " %>

<div class="container-fluid py-5">
  <div class="container">
    <%= render "shared/index", posts: @posts %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/posts/movie.html.erb
<%= render "shared/header" %>

<div class="index-title d-flex align-items-center justify-content-center">
  <div class="h1 text-center text-white font-weight-bold">映画についての投稿</div>
</div>

<% breadcrumb :movie %>
<%= breadcrumbs separator: " &rsaquo; " %>

<div class="container-fluid py-5">
  <div class="container">
    <%= render "shared/index", posts: @posts %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/posts/novel.html.erb
<%= render "shared/header" %>

<div class="index-title d-flex align-items-center justify-content-center">
  <div class="h1 text-center text-white font-weight-bold">小説についての投稿</div>
</div>

<% breadcrumb :novel %>
<%= breadcrumbs separator: " &rsaquo; " %>

<div class="container-fluid py-5">
  <div class="container">
    <%= render "shared/index", posts: @posts %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/posts/show.html.erb
<%= render "shared/header" %>


<div class="index-title d-flex align-items-center justify-content-center">
  <div class="h1 text-center text-white font-weight-bold">投稿詳細ページ</div>
</div>

<% breadcrumb :post, @post %>
<%= breadcrumbs separator: " &rsaquo; " %>

<div class="container-fluid py-5">
  <div class="container" id="test">
    <div class="row justify-content-center">
      <div class="col-8 bg-light shadow p-5">
        <div class="pb-3 border-bottom">
          <div class="mb-2">
            <% if @post.spoiler %>
              <span class="text-danger font-weight-bold btn-sm">ネタバレあり</span>
            <% else %>
              <span class="text-primary font-weight-bold btn-sm">ネタバレなし</span>
            <% end %>
            <span class="post-title"><%= @post.title %></span>
          </div>
          <div class="post-category mb-2 ml-2">
            カテゴリー：<%= @post.category.name %>
          </div>
          <% if user_signed_in? && @post.user_id == current_user.id %>
            <%= link_to "編集する", edit_post_path(@post.id), class:"btn btn-warning btn-sm col-2 ml-1" %>
            <%= link_to "削除する", post_path(@post.id), method: :delete, class:"btn btn-danger btn-sm col-2 ml-1" %>
          <% end %>
        </div>
        <div class="p-3">
          <%=safe_join(@post.content.split("\n"),tag(:br))%>
        </div>
        <div class="row justify-content-around m-3">
          <% Comment.all.length.times do |i| %>
          <div class="col d-flex">
            <% if !user_signed_in? %>
              <span class="comment btn border-primary btn-sm"><%= Comment.find(i+1).name %></span>
            <% elsif @post.reactions.find_by(comment_id: i+1, user_id: current_user.id) %>
              <%= link_to Comment.find(i+1).name, post_reactions_path(@post.id, i+1), method: :delete, remote: true, id:"reaction-btn-#{i+1}-checked", class:"btn btn-sm btn-primary" %>
              <%= link_to Comment.find(i+1).name, post_reactions_path(@post.id, i+1), method: :post, remote: true, id:"reaction-btn-#{i+1}", class:"hidden" %>
            <% else %>
              <%= link_to Comment.find(i+1).name, post_reactions_path(@post.id, i+1), method: :delete, remote: true, id:"reaction-btn-#{i+1}-checked", class:"hidden" %>
              <%= link_to Comment.find(i+1).name, post_reactions_path(@post.id, i+1), method: :post, remote: true, id:"reaction-btn-#{i+1}", class:"btn btn-sm btn-secondary border-primary" %>
            <% end %>
            <% reaction = @post.reactions.where(comment_id: i+1) %>
            <% if reaction %>
              <% reaction_count = reaction.count %>
            <% else %>
              <% reaction_count = 0 %>
            <% end %>
            <%= content_tag(:div, reaction_count, id:"reaction-count-#{i+1}", class:"ml-2") %>
          </div>
          <% end %>
        </div>
        <div class="text-center">
          <%= link_to "投稿一覧に戻る", posts_path %>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container-fruid bg-dark h-100">
    <div class="container h-100">
      <div class="row justify-content-center align-items-center h-50 pt-2 ">
        <%= link_to "運営者", "#", class:"col-2 text-light text-center" %>
        <%= link_to "お問い合わせ", inquiry_new_path, class:"col-2 text-light text-center" %>
        <%= link_to "プライバシーポリシー", "#", class:"col-2 text-light text-center" %>
        <% if user_signed_in? && current_user.id == 1 %>
          <%= link_to "管理人専用", admin_root_path, class:"col-2 text-center" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="header sticky-top border-bottom">
  <nav class="navbar navbar-expand-lg navbar-light bg-dark" style="height: 6vh">
    <%= link_to "トップへ", root_path, class:"navbar-brand text-light ml-3" %>
    <%= link_to "投稿一覧", posts_path, class:"nav-link text-light ml-2" %>
    <%= link_to "小説", novel_posts_path, class:"nav-link text-light ml-2" %>
    <%= link_to "映画", movie_posts_path, class:"nav-link text-light ml-2" %>
    <%= link_to "マンガ", comic_posts_path, class:"nav-link text-light ml-2" %>
    <%= link_to "アニメ", anime_posts_path, class:"nav-link text-light mr-auto ml-2" %>
    
    <div class="navbar-nav">
      <%= form_with url: search_posts_path, method: :get, local: true, class: "d-flex align-items-center" do |f| %>
        <%= f.text_field :keyword, placeholder: "作品を検索する", class: "mr-2 h-75" %>
        <%= f.submit "検索", class: "mr-3 h-75" %>
      <% end %>
      <% if user_signed_in? %>
        <%= link_to "#{current_user.name}さんのマイページ", users_show_path, class:"nav-link text-light" %>
        <%= link_to "新規投稿", new_post_path, class:"nav-link text-light" %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"nav-link text-light mr-3" %>
      <% else %>
        <%= link_to "新規登録", new_user_registration_path, class:"nav-link text-light" %>
        <%= link_to "ログイン", new_user_session_path, class:"nav-link text-light mr-3" %>
      <% end %>
    </div>
  </nav>
</div>

app/views/shared/_index.html.erb
<div class="row justify-content-center w-75 mx-auto bg-light rounded">
  <div class="new-post col-4 text-center border-bottom p-3 my-3 font-weight-bold">みんなの投稿</div>
  <div class="form-group form-check d-flex justify-content-center">
    <input type="checkbox" class="form-check-input mr-1" id="spoiler-check-box">
    <label class="form-check-label">ネタバレを含む投稿を非表示にする</label>
  </div>
  <% posts.each do |post| %>
    <div class="post-wrapper col-9 bg-white border border-primary pt-5 px-5 pb-3 mb-5">
      <%= link_to post_path(post.id), class:"post-link text-dark" do %>
        <div class="mb-2">
          <% if post.spoiler %>
            <span class="text-danger font-weight-bold btn-sm">ネタバレあり</span>
          <% else %>
            <span class="text-primary font-weight-bold btn-sm">ネタバレなし</span>
          <% end %>
          <span class="post-title"><%= post.title %></span>
        </div>
        <div class="mb-2 ml-2">
          カテゴリー：<%= post.category.name %>
        </div>
        <div class="pb-1 border-bottom">
          <% if user_signed_in? && post.user_id == current_user.id %>
            <%= link_to "編集する", edit_post_path(post.id), class:"btn btn-warning btn-sm col-2 ml-1 mb-2" %>
            <%= link_to "削除する", post_path(post.id), method: :delete, class:"btn btn-danger btn-sm col-2 ml-1 mb-2" %>
          <% end %>
        </div>
        <div class="post-content p-3">
          <%=safe_join(post.content.split("\n"),tag(:br))%>
        </div>
        <div class="text-center pt-3">
          "続きを読む"
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<%= render "shared/header" %>

<div class="index-title d-flex align-items-center justify-content-center">
  <div class="h1 text-center text-white font-weight-bold">
    <%= current_user.name %>さんのマイページ
  </div>
</div>

<% breadcrumb :user_page, current_user %>
<%= breadcrumbs separator: " &rsaquo; " %>

<div class="container-fluid py-5">
  <div class="container">
    <div class="row justify-content-center w-75 mx-auto bg-light rounded">
      <div class="new-post col-4 text-center border-bottom p-3 my-3 font-weight-bold">
        <%= current_user.name %>さんの投稿一覧
      </div>
      <div class="w-100"></div>
      <% current_user.posts.reverse_each do |post| %>
        <div class="post-wrapper col-9 bg-white border border-primary pt-5 px-5 pb-3 mb-5">
          <%= link_to post_path(post.id), class:"post-link text-dark" do %>
            <div class="mb-2">
              <% if post.spoiler %>
                <span class="text-danger font-weight-bold btn-sm">ネタバレあり</span>
              <% else %>
                <span class="text-primary font-weight-bold btn-sm">ネタバレなし</span>
              <% end %>
              <span class="post-title"><%= post.title %></span>
            </div>
            <div class="mb-2 ml-2">
              カテゴリー：<%= post.category.name %>
            </div>
            <div class="pb-1 border-bottom">
              <%= link_to "編集する", edit_post_path(post.id), class:"btn btn-warning btn-sm col-2 ml-1 mb-2" %>
              <%= link_to "削除する", post_path(post.id), method: :delete, class:"btn btn-danger btn-sm col-2 ml-1 mb-2" %>
            </div>
            <div class="post-content p-3">
              <%=safe_join(post.content.split("\n"),tag(:br))%>
            </div>
            <div class="text-center pt-3">
              <%= link_to "続きを読む", post_path(post.id) %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= render "shared/footer" %>